### ISSUE TITLE
As a service user, I want to know where I am in the app so that I don't feel lost along the way.

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#17]
- [ ] Tree of wellbeing
- [ ] Some form of navigation
- [ ] Ability to move back and forth between stages
- [ ] Hamburger menu
