### ISSUE TITLE
Create Figma

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#29]
- [x] Find font
- [x] Decide on navigation 
- [x] Create landing page
- [ ] Create navigation instruction page
- [x] Create disclaimer page
- [x] Create consent page
- [x] Create user contact page
- [x] Create eligiblity criteria page
- [x] Create outcomes page
- [x] Create overview
- [x] Create send page
