### ISSUE TITLE
FOR RACHEL: CURRENT TASKS AFTER RESEARCH WEEK 1

### ISSUE THREAD

**Issue by teenie-quaggard** [the-advocacy-project/advocacy-app#46]
- [x] Sending and following up with copy (see #42)
- 'Feel free to ask a volunteer' should be inclusive of all staff related to The Advoacy Project

- [x] Providing an email template (see #36)
- [x] Whos is LBH? (see # 37) This is a screen grab from the initial fact finding (#2)
![screen shot 2019-02-08 at 19 34 56](https://user-images.githubusercontent.com/37771591/52501772-0dbe8c80-2bd9-11e9-9639-df3e9939713c.png)

**Comment by rachel-butt** [comment]
LBH is London Bourough of Hackney :)
